SofaBot/SofaBot/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^SofaBotApp/', include('SofaBotApp.urls')),
    url(r'^admin/', admin.site.urls),
]

SofaBot/SofaBotApp/urls.py
from django.conf.urls import url


from . import views

app_name = 'SofaBotApp'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^updateExchange/$', views.updateExchange, name='updateExchange'),
    url(r'^addBot/$', views.addBot, name='addBot'),
    url(r'^(?P<exchange_id>[0-9]+)/startExchange/$', views.startExchange, name='startExchange'),
    url(r'^(?P<exchange_id>[0-9]+)/deleteExchange/$', views.deleteExchange, name='deleteExchange'),
    url(r'^(?P<exchange_id>[0-9]+)/stopExchange/$', views.stopExchange, name='stopExchange'),
    url(r'^getOrderStateList/$', views.getOrderStateList, name='getOrderStateList'),
]

SofaBot/SofaBotApp/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

import datetime

from django.utils import timezone

@python_2_unicode_compatible
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

@python_2_unicode_compatible
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

@python_2_unicode_compatible
class Exchange(models.Model):
    currency_pair = models.CharField(max_length=20)
    currency_default = models.CharField(max_length=20)
    currency_investing = models.CharField(max_length=20)
    initial_btc = models.FloatField(default=0)
    isActive    = models.BooleanField(default=False)

    def __str__(self):
        return self.currency_pair



@python_2_unicode_compatible
class OrderState(models.Model):
    exchange = models.ForeignKey(Exchange, on_delete=models.CASCADE)
    orderNumber = models.BigIntegerField(default=0)
    statusCode = models.IntegerField(default=0)
    perGain = models.FloatField(default=0)
    actual_price = models.FloatField(default=0)
    buy_value = models.FloatField(default=0)
    sell_value = models.FloatField(default=0)
    current_btc = models.FloatField(default=0)
    current_coin = models.FloatField(default=0)
    piggy       = models.FloatField(default=0)
    state_date = models.DateTimeField('date state')
    currency_pair = models.CharField(max_length=20)

    def __str__(self):
        return str(self.statusCode)

SofaBot/SofaBotApp/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.shortcuts import render_to_response, redirect
from django.http import JsonResponse

from .utils.Trader import Trader
from .utils.Bitfinex import BitFinex
from .models import Exchange, OrderState, Question, Choice

from django.utils import timezone
from django.core import serializers
from django.contrib import messages
import json
import pdb;
from django.core.serializers.json import DjangoJSONEncoder

market = BitFinex()

class IndexView(generic.ListView):

    template_name = 'SofaBotApp/index.html'
    context_object_name = 'exchange_list'


    def get_queryset(self):

        return Exchange.objects.order_by('id')[:]

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)

        context['max_default_currency'] = market.parseMaxDefaultCurrency()
        context['wallets'] = market.parseWalletsToDict()

        dict_coin = {}
        for idx , pairCurrency in enumerate(market.getPairCurrencies()):

                dict_coin[idx] = pairCurrency

        context['coins'] = dict_coin
        context['success_message'] = self.request.session.get('success_message')  # get the value from session
        context['error_message'] = self.request.session.get('error_message')  # get the value from session
        self.request.session['error_message'] = None
        self.request.session['success_message'] = None

        return context


class DetailView(generic.DetailView):
    model = Question
    template_name = 'SofaBotApp/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'SofaBotApp/results.html'


def vote(request, question_id):

    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'SofaBotApp/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('results', args=(question.id,)))


def updateExchange(request):

    listOrders = []

    for e in Exchange.objects.all():
        o = e.orderstate_set.last()
        listOrders.append(o)

    json = serializers.serialize('json', listOrders)

    return HttpResponse(json, 'application/json')

def addBot(request):

    currency_pair = request.POST['currency_pair']
    initial_btc = request.POST['initial_btc']

    try:
        e = Exchange.objects.get(currency_pair=currency_pair)

        request.session['error_message'] =  currency_pair + " ja foi adicionado."
        return redirect("/SofaBotApp/")

    except Exchange.DoesNotExist:
        e = Exchange(currency_pair= currency_pair, initial_btc= initial_btc)
        e.save()
        e.orderstate_set.create(state_date=timezone.now(), current_btc=initial_btc)
        e.save()

        request.session['success_message'] = currency_pair + " adicionado com sucesso."
        return redirect("/SofaBotApp/")

    except Exception as ex:

        print  ex

        request.session['error_message'] = "Ocorreu um erro ao adicionar " + currency_pair
        return redirect("/SofaBotApp/")

def startExchange(request, exchange_id):

    try:
        e = get_object_or_404(Exchange, pk=exchange_id)
        e.isActive = True
        e.save()

        trader = Trader(exchange_id, market)
        trader.start()

        request.session['success_message'] = e.currency_pair + " iniciado com sucesso."
        return redirect("/SofaBotApp/")

    except Exception as ex:

        request.session['error_message'] = "Ocorreu um erro ao iniciar"
        return redirect("/SofaBotApp/")

def deleteExchange(request, exchange_id):

    try:
        e = get_object_or_404(Exchange, pk=exchange_id)
        e.delete()

        request.session['success_message'] = e.currency_pair + " deletado com sucesso."
        return redirect("/SofaBotApp/")

    except Exception as ex:

        request.session['error_message'] = "Ocorreu um erro ao deletar"
        return redirect("/SofaBotApp/")

def stopExchange(request, exchange_id):

    try:
        e = get_object_or_404(Exchange, pk=exchange_id)
        e.isActive = False
        e.save()

        request.session['success_message'] = e.currency_pair + " parado com sucesso."
        return redirect("/SofaBotApp/")

    except Exception as ex:

        request.session['error_message'] = "Ocorreu um erro ao parar"
        return redirect("/SofaBotApp/")

def getOrderStateList(request):

    try:
        exchangeId = int(request.GET['exchangeId'])
        e = get_object_or_404(Exchange, pk=exchangeId)

        return render(request, 'SofaBotApp/getOrderStateList.html', {'exchange': e})

    except Exception as ex:

        print ex
        request.session['error_message'] = "Ocorreu um buscar detalhes de exchange"
        return redirect("/SofaBotApp/")

SofaBot/SofaBotApp/templates/SofaBotApp/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'SofaBotApp:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

SofaBot/SofaBotApp/templates/SofaBotApp/getOrderStateList.html
<div class="container">
<div class="col-md-10">
    <h1>{{exchange.currency_pair}}</h1>
   <table class="table">
    <thead>
    <tr>
        <th>Date</th>
        <th>Buy Value</th>
        <th>Sell Value</th>
        <th>Actual Value</th>
        <th>Current BTC</th>
        <th>Current Coin</th>
        <th>Piggy</th>
        <th>Gain/Loss</th>
        <th>Status</th>
    </tr>
    </thead>
    <tbody>
    {% for order in exchange.orderstate_set.all %}
      <tr {% if order.statusCode != 0 %} bgcolor="#56c0e0" {% endif %}>
         <td>{{ order.state_date }}</td>
         <td>{{ order.buy_value|floatformat:5 }}</td>
         <td>{{ order.sell_value|floatformat:5 }}</td>
         <td>{{ order.actual_price|floatformat:5 }}</td>
         <td>{{ order.current_btc|floatformat:5 }}</td>
         <td>{{ order.current_coin|floatformat:5 }}</td>
         <td>{{ order.piggy|floatformat:5 }}</td>
         <td>{{ order.perGain|floatformat:2 }}</td>
         <td >{{ order.statusCode }}</td>
      </tr>
    {% endfor %}
    </tbody>
    </table>
</div>
</div>

SofaBot/SofaBotApp/templates/SofaBotApp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SofaBot</title>

    <!-- Bootstrap -->
    <link href="{% static "SofaBotApp/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "SofaBotApp/css/sofabot.css" %}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <script>
        var append_increment = 0;
        setInterval(function() {

            $.ajax({
              url: "{% url 'SofaBotApp:updateExchange' %}",
              success: function(json) {


                    for(var i in json)
                    {
                       var orderState = json[i]['fields']

                       $('#' + orderState['exchange'] + '_buy_value').html(orderState['buy_value']);
                       $('#' + orderState['exchange'] + '_sell_value').html(orderState['sell_value']);
                       $('#' + orderState['exchange'] + '_actual_price').html(orderState['actual_price']);
                       $('#' + orderState['exchange'] + '_statusCode').html(orderState['statusCode']);
                       $('#' + orderState['exchange'] + '_current_btc').html(orderState['current_btc']);
                       $('#' + orderState['exchange'] + '_current_coin').html(orderState['current_coin']);
                       $('#' + orderState['exchange'] + '_piggy').html(orderState['piggy']);

                    }
               }
            });
        }, 30000)

        function getOrderStateList(exchangeId)
        {
            $.ajax({
                  type: "GET",
                  url: "{% url 'SofaBotApp:getOrderStateList' %}",
                  data: {'exchangeId': exchangeId},
                  success: function(response) {

                       $('#orderStateListDiv').html(response);
                   }
                });
        }

    </script>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">

            <a class="navbar-brand" href="#">SofaBot</a>
            <img src="{% static "SofaBotApp/img/sofa_icon.png" %}" />
        </div>
    </div>
</nav>

<div class="container theme-showcase" role="main">

    {% if error_message %}
        <div class="alert alert-danger" role="alert">
             <strong>Erro</strong> {{error_message}}
        </div>
    {% elif success_message%}
        <div class="alert alert-success" role="alert">
             <strong>Sucesso</strong> {{success_message}}
        </div>
    {% endif%}

    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal">Criar Bot</button>
      <!-- Modal -->
      <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">


          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">Criar Bot</h4>
            </div>
            <form action="{% url 'SofaBotApp:addBot' %}" method="post">
            {% csrf_token %}
            <div class="container">

                <div class="form-group col-md-6">
                  <label for="currency_pair">Select exchange:</label>
                  <select class="form-control" name="currency_pair" id="currency_pair" title="currency_pair">
                       {% for k, v in coins.items %}
                        <option>{{v}}</option>
                      {% endfor %}
                  </select>
                  <br>
                  <label>Select quantity:</label>
                  <div class="container">
                    <div class="row">
                        <div class="col-sm-1">
                            <input type="number" name="initial_btc" id="initial_btc" min="0" max={{max_default_currency}} step="0.001" data-bind="value:initial_btc" />
                        </div>
                        <div class="col-sm-3">
                            <label>BTC: <span class="label label-default">{{max_default_currency}}</span></label>
                        </div>
                    </div>
                  </div>
                </div>


            </div>

            <div class="modal-footer">
              <button type="submit" class="btn btn-primary" >Adicionar</button>
            </div>

            </form>
            </div>
        </div>
      </div>

     <!-- Modal -->
          <div class="modal fade" id="orderListModal" role="dialog">
            <div class="modal-dialog modal-xl">


              <!-- Modal content-->
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title">Detalhes</h4>
                </div>
                <div id="orderStateListDiv">

                </div>

                </div>
            </div>
          </div>


    <div class="row">

        <div class="col-md-10">
           <table class="table">
            <thead>
            <tr>
                <th>#</th>
                <th>Exchange</th>
                <th>Initial BTC</th>
                <th>Buy Value</th>
                <th>Sell Value</th>
                <th>Actual Value</th>
                <th>Status</th>
                <th>Current BTC</th>
                <th>Current Coin</th>
                <th>Piggy</th>
                <th>Active</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            {% if exchange_list %}
            {% for exchange in exchange_list %}
            <tr>

                <td><label>{{ exchange.id }}</label></td>
                <td><label>{{ exchange.currency_pair }}</label></td>
                <td><label >{{ exchange.initial_btc   }}</label></td>
                <td><label id='{{exchange.id}}_buy_value'>{{ exchange.orderstate_set.last.buy_value }}</label></td>
                <td><label id='{{exchange.id}}_sell_value'>{{ exchange.orderstate_set.last.sell_value }}</label></td>
                <td><label id='{{exchange.id}}_actual_price'></label></td>
                <td><label id='{{exchange.id}}_statusCode'>{{ exchange.orderstate_set.last.statusCode  }}</label></td>
                <td><label id='{{exchange.id}}_current_btc'>{{ exchange.orderstate_set.last.current_btc   }}</label></td>
                <td><label id='{{exchange.id}}_current_coin'>{{ exchange.orderstate_set.last.current_coin   }}</label></td>
                <td><label id='{{exchange.id}}_piggy'>{{ exchange.orderstate_set.last.piggy }}</label></td>
                <td><label>{{ exchange.isActive }}</label></td>
                <td>
                    {% if exchange.isActive %}
                    <a
                        class="btn btn-danger"
                        href="{% url 'SofaBotApp:stopExchange' exchange.id %}">
                        <span class="glyphicon glyphicon-ban-circle"></span>
                    </a>
                    {% else %}
                    <a
                        class="btn btn-success"
                        href="{% url 'SofaBotApp:startExchange' exchange.id %}">
                        <span class="glyphicon glyphicon-play-circle"></span>
                    </a>

                    {% endif %}
                    <button type="button" class="btn btn-info" data-toggle="modal" data-target="#orderListModal" onclick="getOrderStateList({{exchange.id}})"> <span class="glyphicon glyphicon-list-alt"></span> </button>
                    <a
                        class="btn btn-danger"
                        href="{% url 'SofaBotApp:deleteExchange' exchange.id %}">
                        <span class="glyphicon glyphicon-play-circle"></span>
                    </a>
                </td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="12"><center>No bots available.</center></td>
            </tr>
            {% endif %}
            </tbody>
            </table>
        </div>
         <div class="col-md-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Wallet</h3>
                </div>
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Coin</th>
                                <th>Balance</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if wallets %}

                                {% for k, v in wallets.items %}
                                <tr>
                                    <td>{{k}}</td>
                                    <td>{{v}}</td>
                                </tr>
                                {% endfor %}
                            {% else %}
                            <tr><td>No wallet</td></tr>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
      </div>

</div>


<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->

<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static "SofaBotApp/js/bootstrap.min.js" %}"></script>

</body>
</html>

SofaBot/SofaBotApp/templates/SofaBotApp/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'detail' question.id %}">Vote again?</a>